### ISSUE TITLE
Chromosome names are cut of at dots

### ISSUE THREAD

**Issue by patrick-barth** [ramiromagno/wig#1]
As the titles says chromosome names are cut off when a dot is encountered in them
Example header line: 
`variableStep chrom=DQ380182.1 span=1` 
becomes
`DQ380182`

**Comment by ramiromagno** [comment]
Hi Patrick,

Thank you for spending the time raising this issue.

Please try the development version of the package and check whether the issue has been resolved.

**Comment by patrick-barth** [comment]
Thank you for the quick answer and sorry for my late one.

I just tested it and the problem seems to persist.

Just to be sure that I tested the correct version. I can reach the development version with following commands, right?

`dev_mode(on=T)`
`install_github(ramiromagno/wig)`
`import_wig(file)`

**Comment by ramiromagno** [comment]
Indeed, `install_github(ramiromagno/wig)` installs the development version. But then you need to make sure that the new installed package is loaded with `library(wig)`. If you had `wig` already loaded and you ran `library(wig)`, then R won't load wig again. So you might still have been using the old package version. Just make sure you start a new R session.

If after starting a new session, then loading wig, the problem still persists, then could you provide a small example file so that I can test?

**Comment by patrick-barth** [comment]
It works!!
My problem was that I loaded the old package before the development version and the development version afterwards. `session_info()` showed me the development version one but apparently there was a path mismatch.

Thank you a lot :)
